Repository marcosb1/Java-Resource-Manager, pull requests merged in 2018-04, with the labels that each got.

#15 Test for application launch created.
  pom.xml
  src/main/java/com/marist/jrm/client/GUIDriver.java
  src/test/java/com/marist/jrm/client/GUIDriverTest.java
Labels: cleanup

#18 Synchronizing branches
  jrm1.DB
  pom.xml
  sqlLiteDDL.txt
  src/main/java/com/marist/jrm/application/ApplicationDriver.java
  src/main/java/com/marist/jrm/application/SQLiteDBInit.java
  src/main/java/com/marist/jrm/application/SQLiteDBUtil.java
  src/main/java/com/marist/jrm/application/SQLiteJDBCDriverConnection.java
  src/resources/jrmDB.db
  src/test/java/com/marist/jrm/application/SQLiteDBUtilTest.java
Labels: cleanup

#19 Catch up application-package-dev
  log
  pom.xml
  seperateProcessDir/plchold.txt
  src/main/java/com/marist/jrm/application/SQLiteDBUtilTest.java
  src/main/java/com/marist/jrm/model/Process.java
  src/main/java/com/marist/jrm/systemCall/SystemCallDriver.java
  src/resources/jrmDB.db
  src/test/java/com/marist/jrm/application/SQLiteDBUtilTest.java
  src/test/java/com/marist/jrm/systemCall/GenerateProcess.java
  src/test/java/com/marist/jrm/systemCall/SystemCallTestSuite.java
  src/test/java/com/marist/jrm/systemCall/TestThreads.java
  src/test/java/com/marist/jrm/systemCall/TestValidProcesses.java
Labels: cleanup

#26 Avoiding conflicts for next deliverable.
  log
  pom.xml
  seperateProcessDir/plchold.txt
  src/main/java/com/marist/jrm/ApplicationModel.java
  src/main/java/com/marist/jrm/ProcessModel.java
  src/main/java/com/marist/jrm/systemCall/SystemCallDriver.java
  src/resources/jrmDB.db
  src/test/java/com/marist/jrm/systemCall/GenerateProcess.java
  src/test/java/com/marist/jrm/systemCall/SystemCallTestSuite.java
  src/test/java/com/marist/jrm/systemCall/TestThreads.java
  src/test/java/com/marist/jrm/systemCall/TestValidProcesses.java
Labels: cleanup

#32 System call package
  src/main/java/com/marist/jrm/client/GUIDriver.java
  src/main/java/com/marist/jrm/systemCall/SystemCallDriver.java
  src/test/java/com/marist/jrm/systemCall/SystemCallTestSuite.java
Labels: cleanup

#33 Build dev
  sqlLiteDDL.txt
  src/main/java/com/marist/jrm/application/ApplicationDriver.java
  src/main/java/com/marist/jrm/application/SQLiteDBInit.java
  src/main/java/com/marist/jrm/application/SQLiteDBUtil.java
  src/main/java/com/marist/jrm/application/SQLiteJDBCDriverConnection.java
  src/main/java/com/marist/jrm/client/GUIDriver.java
  src/main/java/com/marist/jrm/model/ApplicationModel.java
  src/main/java/com/marist/jrm/systemCall/SystemCallDriver.java
  src/resources/jrmDB.db
  src/test/java/com/marist/jrm/application/SQLiteDBUtilTest.java
  src/test/java/com/marist/jrm/systemCall/SystemCallTestSuite.java
Labels: cleanup

#34 Build dev
  .gitignore
  jrm1.DB
  pom.xml
  seperateProcessDir/plchold.txt
  sqlLiteDDL.txt
  src/main/java/com/marist/jrm/application/ApplicationDriver.java
  src/main/java/com/marist/jrm/application/SQLiteDBInit.java
  src/main/java/com/marist/jrm/application/SQLiteDBUtil.java
  src/main/java/com/marist/jrm/application/SQLiteJDBCDriverConnection.java
  src/main/java/com/marist/jrm/client/GUIDriver.java
  src/main/java/com/marist/jrm/model/Application.java
  src/main/java/com/marist/jrm/model/ApplicationModel.java
  src/main/java/com/marist/jrm/model/Process.java
  src/main/java/com/marist/jrm/model/ProcessModel.java
  src/main/java/com/marist/jrm/systemCall/SystemCallDriver.java
  src/resources/jrmDB.db
  src/test/java/com/marist/jrm/application/SQLiteDBUtilTest.java
  src/test/java/com/marist/jrm/client/GUIDriverTest.java
  src/test/java/com/marist/jrm/systemCall/GenerateProcess.java
  src/test/java/com/marist/jrm/systemCall/TestThreads.java
  src/test/java/com/marist/jrm/systemCall/TestValidProcesses.java
Labels: cleanup

#35 Merging format and logging changes along with added dbInit to the gui start()
  .gitignore
  src/main/java/com/marist/jrm/application/ApplicationDriver.java
  src/main/java/com/marist/jrm/application/SQLiteDBInit.java
  src/main/java/com/marist/jrm/application/SQLiteDBUtil.java
  src/main/java/com/marist/jrm/application/SQLiteJDBCDriverConnection.java
  src/main/java/com/marist/jrm/client/GUIDriver.java
  src/resources/jrmDB.db
  src/test/java/com/marist/jrm/application/SQLiteDBUtilTest.java
Labels: cleanup

#37 Cleanup for final presentation
  .gitignore
  src/main/java/com/marist/jrm/application/ApplicationDriver.java
  src/main/java/com/marist/jrm/application/SQLiteDBInit.java
  src/main/java/com/marist/jrm/application/SQLiteDBUtil.java
  src/main/java/com/marist/jrm/application/SQLiteJDBCDriverConnection.java
  src/main/java/com/marist/jrm/client/GUIDriver.java
  src/main/java/com/marist/jrm/model/ApplicationModel.java
  src/main/java/com/marist/jrm/model/MemoryMetrics.java
  src/main/java/com/marist/jrm/systemCall/SystemCallDriver.java
  src/resources/jrmDB.db
  src/test/java/com/marist/jrm/application/SQLiteDBUtilTest.java
  src/test/java/com/marist/jrm/systemCall/TestThreads.java
  src/test/java/com/marist/jrm/systemCall/TestValidProcesses.java
  src/test/main/java/com/marist/jrm/client/GUIDriverApplicationTabTest.java
  src/test/main/java/com/marist/jrm/client/GUIDriverProcessTabTest.java
Labels: cleanup

#41 Testing graph output
  src/main/java/com/marist/jrm/client/GUIDriver.java
  src/main/java/com/marist/jrm/model/MemoryMetrics.java
  src/main/java/com/marist/jrm/systemCall/SystemCallDriver.java
  src/test/java/com/marist/jrm/systemCall/TestValidProcesses.java
Labels: cleanup

#42 Application package dev
  src/main/java/com/marist/jrm/application/SQLiteDBInit.java
  src/main/java/com/marist/jrm/application/SQLiteDBUtil.java
  src/main/java/com/marist/jrm/client/GUIDriver.java
  src/resources/jrmDB.db
  src/test/java/com/marist/jrm/application/SQLiteDBUtilTest.java
Labels: enhancement, feature

#44 Fixing compile errors from last PR
  src/main/java/com/marist/jrm/client/GUIDriver.java
Labels: bug

#46 Project complete
  src/main/java/com/marist/jrm/application/ApplicationDriver.java
  src/main/java/com/marist/jrm/application/SQLiteDBInit.java
  src/main/java/com/marist/jrm/application/SQLiteDBUtil.java
  src/main/java/com/marist/jrm/application/SQLiteJDBCDriverConnection.java
  src/main/java/com/marist/jrm/client/GUIDriver.java
  src/resources/jrmDB.db
Labels: cleanup

#47 Syncing branches
  src/main/java/com/marist/jrm/application/SQLiteDBInit.java
  src/main/java/com/marist/jrm/application/SQLiteDBUtil.java
  src/main/java/com/marist/jrm/application/SQLiteJDBCDriverConnection.java
  src/main/java/com/marist/jrm/client/GUIDriver.java
  src/main/java/com/marist/jrm/client/components/ConfirmBox.java
  src/main/java/com/marist/jrm/model/ApplicationModel.java
  src/main/java/com/marist/jrm/model/MemoryMetrics.java
  src/main/java/com/marist/jrm/model/ProcessModel.java
  src/main/java/com/marist/jrm/systemCall/SystemCallDriver.java
  src/resources/jrmDB.db
Labels: cleanup
